title: "Watery Theme for Jekyll \U0001F6B0"
email: mail@brennanbrown.ca
description: >-
  A minimalist, bare-bones theme for Jekyll only using the Water.css framework
  while still following the best practices possible for accessibility and
  search-engine optimization.
baseurl: ''
url: ''
repository: brennanbrown/watery
twitter: brennankbrown
github: brennanbrown
google_analytics: null
comments: true
disqus: watery-jekyll
author: Brennan K. Brown
author_bio: "Hey there! \U0001F604 My name is Brennan, I'm a 24-year-old Métis web developer and  content strategist from Winnipeg, Manitoba and currently reside in Calgary,  Alberta. I've recently compeleted a Full Stack Developer Program at EvolveU,  and I'm looking to help those that need web development work done, or  searching for ideas and management for their next content project."
author_pic: 'https://brennanbrown.ca/img/avatar.png'
paginate: 4
paginate_path: '/:num/'
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: '/:title'
theme_switcher: true
collections:
  pages:
    output: true
    permalink: '/:title'
exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
